# Generated by Django 5.2.7 on 2025-10-26 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_remove_coupon_usage_limit'),
        ('order', '0005_orderitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
