# Generated by Django 5.2.7 on 2025-10-26 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
    ]
