# Generated by Django 5.2.7 on 2025-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_remove_coupon_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='reward_given',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
