# Generated by Django 5.2.7 on 2025-10-15 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderpayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('phone_number', models.CharField(max_length=30)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_paytment', to='order.order')),
            ],
        ),
    ]
