# Generated by Django 5.2.7 on 2025-10-15 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='Product',
            new_name='product',
        ),
    ]
