# Generated by Django 5.2.7 on 2025-10-28 13:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('model_version', models.CharField(default='v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='product.product')),
                ('similar_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='product.product')),
            ],
            options={
                'ordering': ['-score'],
                'indexes': [models.Index(fields=['product', 'score'], name='recommendat_product_677641_idx'), models.Index(fields=['model_version'], name='recommendat_model_v_adb97b_idx')],
                'unique_together': {('product', 'similar_product')},
            },
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add to cart'), ('purchase', 'Purchase'), ('search', 'Search'), ('click', 'Click'), ('not_interested', 'Not interested')], max_length=30)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, help_text='Optional additional info (e.g. search query, source)', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to='order.orderitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to='product.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'product'], name='recommendat_user_id_d6081c_idx'), models.Index(fields=['action'], name='recommendat_action_076936_idx'), models.Index(fields=['timestamp'], name='recommendat_timesta_aea04f_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_product_ids', models.JSONField(default=list, help_text='Ordered list of recommended product ids')),
                ('model_version', models.CharField(default='v1', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user'], name='recommendat_user_id_c0ae45_idx'), models.Index(fields=['model_version'], name='recommendat_model_v_32d312_idx')],
            },
        ),
    ]
