# Generated by Django 5.2.7 on 2025-10-19 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_orderitem_created_at'),
        ('product', '0003_productrating'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('model_version', models.CharField(default='v1', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
        migrations.CreateModel(
            name='UserRecommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_product_ids', models.JSONField(default=list, help_text='Ordered list of recommended product ids')),
                ('model_version', models.CharField(default='v1', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='purchase',
        ),
        migrations.AddField(
            model_name='useraction',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional additional info (e.g. search query, source)', null=True),
        ),
        migrations.AddField(
            model_name='useraction',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to='order.orderitem'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to='product.product'),
        ),
        migrations.AddField(
            model_name='useraction',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('add_to_cart', 'Add to cart'), ('purchase', 'Purchase'), ('search', 'Search'), ('click', 'Click'), ('not_interested', 'Not interested')], max_length=30),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendation_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['user', 'product'], name='recommendat_user_id_d6081c_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['action'], name='recommendat_action_076936_idx'),
        ),
        migrations.AddIndex(
            model_name='useraction',
            index=models.Index(fields=['timestamp'], name='recommendat_timesta_aea04f_idx'),
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_to', to='product.product'),
        ),
        migrations.AddField(
            model_name='itemsimilarity',
            name='similar_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similar_from', to='product.product'),
        ),
        migrations.AddField(
            model_name='userrecommendations',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='itemsimilarity',
            index=models.Index(fields=['product', 'score'], name='recommendat_product_677641_idx'),
        ),
        migrations.AddIndex(
            model_name='itemsimilarity',
            index=models.Index(fields=['model_version'], name='recommendat_model_v_adb97b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='itemsimilarity',
            unique_together={('product', 'similar_product')},
        ),
        migrations.AddIndex(
            model_name='userrecommendations',
            index=models.Index(fields=['user'], name='recommendat_user_id_c0ae45_idx'),
        ),
        migrations.AddIndex(
            model_name='userrecommendations',
            index=models.Index(fields=['model_version'], name='recommendat_model_v_32d312_idx'),
        ),
    ]
